### PR TITLE
Upgrade to .NET Core 3.1

### PR DESCRIPTION
**Pull request by themaroqa**
This PR is for pgrading badgie-migrator to .NET Core 3.1. 
Simply because .NET 2.2 is out of support and is not downloadable anymore.

### CODE REVIEW

**Review by sklivvz — DISMISSED** [review]

**Comment by sklivvz** [comment]
Please try to build and run tests before submitting (tests fail)

image

**Review by sklivvz — CHANGES_REQUESTED** [review]
Target framework must be changed in all projects and tests must pass

**Comment by themaroqa** [comment]
Will fix, wasn't able to see the actual error. Thx

**Comment by themaroqa** [comment]
Locally builds and tests run

**Comment by themaroqa** [comment]
gentle reminder for @sklivvz

**Review by sklivvz — APPROVED** [review]

**Pull request merged**
